fossasia/susi_chromebot

src/manifest.json
Fixes #105
- [x ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ x] My branch is up-to-date with the Upstream `nextgen` branch.
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] I have added necessary documentation (if appropriate)
This is exactly similar to PR [https://github.com/fossasia/susi_firefoxbot/pull/36](url) by nifey who adds this feature in susi_firefoxbot . Same changes are compatible in manifest.json of chromebot.
So should I ask him instead to send the PR ? 
- For quicker access to the popup type (ALT+SHIFT+S)
-
-
=> add keyboard shortcut for susi popup

src/manifest.json, src/script.js
Fixes  #97 
Make the chat data persistent so that closing extension does not result in losing the previous chat results. 
- change `manifest.json` to include `storage` permissions
- use `chrome.storage.sync` to store chat data
=> make chat data persistent

src/script.js
Fixes #142 
The dark theme gets reset to default everytime the user closes and reopens the extension. This fixes it by storing theme state.
=> Fix dark theme automatic switch

src/style.css
Fixes #150 
The scroll-bar and messages are too close, leaving extra space on the right side of scroll-bar
- Add padding in between scroll-bar and messages
=> Fixes #150 : Add padding in between scroll-bar and messages

src/background.js, src/manifest.json, src/script.js
Fixes #144 
Adds a context menu - "Ask SUSI". User can select any text in any webpage, right click on it, select "Ask SUSI" option. The query will be visible in the SUSI popup, when the user will open the popup. (programmatic opening of the extension's popup is not supported in chrome. See [here](https://stackoverflow.com/questions/5544256/chrome-extensionhow-to-pragmatically-open-the-popup-window-from-background-htm) )
- add "contextMenus" permission in `manifest.json` file.
- Add a context menu "Ask SUSI".
- Asks SUSI for the selected text.
- Add a badge(`*`) in the icon of the extension when the user clicks on the context menu, indicating unread message.
- Remove the badge from the icon of the extension when the user opens the extension.
=> fix #144 - Add context menu on text selection and right click

src/script.js
Fixes #167 
Apply dark theme on the loading icon message
- Check if dark theme is enabled or not. 
- If it is enabled, apply it to the loading message
- If it is not enabled, apply the light theme to the loading message
=> Fix #167 - apply dark theme to loading message

src/script.js
Fixes #241
Previously the old chat history was not exported
Now the old chat history is also exported
=> Now the json export button exports old chat history

src/css/signup.css, src/js/signup.js, src/login.html, src/signup.html
Fixes #230 
Added option of signup from the chromebot
=> Add signup option

src/js/allowmic.js
Fixes #310
Redundant code was present in the code file, `allowmic.js` (two if else bloacks being repeated), removed it.
- Removed the redundant code.
-
-
=> Remove redundant code

src/js/reset.js, src/login.html, src/recover.html
Fixes #325 
- [] I have added necessary documentation (if appropriate)
Indicates user if the field is required after submitting the forms - `Change Password` and `Forget Password`.
- Uses HTML `required` attribute in the input fields to achieve the same. 
- Removes `alert` in Forget password.
=> Add required attribute in input fields.

src/script.js
Fixes #323
Earlier we had overlapping message on previous chat. Also although I was logged in, it was showing `log in` option in dropdown, Instead it should have been `Logout`.
Solved this. It will check if user email if logged in and then set the access token. Earlier it was checking access token and user email, but access token wasn't present at all/set!
=> Remove wrong check if user is logged in.

src/popup.html
Fixes #332 
Now scroll icon is below the dropdown.
- Changed the z-index of dropdown to 2, and of scroll icon to 1.
- not able to Change stack-order/ z-index property even after setting up the propoerty to 1;
refer https://leafletjs.com/reference-1.3.4.html#tilelayer-zindex
=> Add stack order of dropdown higher than scroll icon

src/css/login.css, src/login.html
Fixes #346 
Corrects the sizing of only misaligned `change password` form on small-screen size.
- changed Placeholder from `NewPassword` to `New Password`.
-  Resize the form, add auto margin.
- Center the link `Click here to change password`.
**changes done**:
=>  Correct change Password form size

src/js/background.js, src/manifest.json
Fixes #343
Option to go to https://chat.susi.ai , https://skills.susi.ai
####Screenshot
- Created context menu
- Context event listener to open a new tab in chrome
=> Add Susi Chat, Susi Skills shortcut in Option menu #343

src/css/login.css, src/css/signup.css, src/js/login.js, src/js/signup.js, src/login.html, src/signup.html
Fixes #326 
it gives a user info about `minimum password limit of 6`, both at setting up new password (at signup) and changing password (in change password form). Help text gets removed, if user enters characters greater than 5.
- Color of warning/infp text is set to white, as `red` is not showing up clearly on a blue background.
- Text is centered.
=> Add minimum password limit for the user

src/js/signup.js, src/signup.html
Fixes #379 
**Earlier** id `cpassword` was used in setting up password field on sign up form.
Whereas id `password` was used in confirmation password field on sign up form.
Refer https://github.com/fossasia/susi_chromebot/blob/b9af60cade7b8d054754f923dc77a4379d333a5f/src/signup.html#L25
https://github.com/fossasia/susi_chromebot/blob/b9af60cade7b8d054754f923dc77a4379d333a5f/src/signup.html#L30
- Now, made the  `password` id for **password** field and `cpassword` id for **confirm password** field.
- Change corresponding Javascript file.
------
@zamhaq @gabru-md @ms10398 @stealthanthrax please review.
=> exchange ID names of cpassword with password.

src/css/login.css, src/script.js, src/style.css
Fixes #373, #358, #378 
On typing something gibberish or like random letters, no response is fetched(only loading). Now a response is shown.
When reply is of tweet type, the response is not cutoff from right side now.
The eye is inside the password field.
Screenshot:
For non response
For table:
For eye:
- On typing something gibberish or like random letters, `Respond with Hmm... I'm not sure if i understand you correctly.`
- Fixed table tweet response text, it wont cut like it used to earlier.
- Fix the eye inside input field
=> Respond with text if Response Empty #373, Table Cut #358

.github/ISSUE_TEMPLATE.md
Fixes #330 - using the old issue for this PR.
Typo
- Should be `our` instead of `out`.
=> Fix typo. Replace 'out' with 'our'

.jshintrc, Gruntfile.js, src/script.js
Fixes #289 
Bot speaks out every reply from the start on re-install/re-login. Now it wouldn't happen.
-  if messages are being synced from the server, then `successResponse` should be called with speak set to false. And thus susi will not speak older messages. Default value of `speak` is set to true, for all other cases.
=> Stop SUSI from speaking out earlier messages on login.

src/js/options.js, src/options.html, src/popup.html
Fixes #384 #348 
Changed the name of `allowmic.js` to `options.js`. Refer #382 for more details.
Added a option/button to restore default settings, by clearing up the localStorage items stored by the user.
=> Rename allowmic.js and add button to restore default settings.

src/js/options.js
Fixes #410 
- Using Latest Code to stop Voice Streams
=> Fix -410 Removing Deprecated Stream.stop

src/js/login.js, src/login.html, src/script.js
Fixes #366, #382, #402
Closed PR https://github.com/fossasia/susi_chromebot/pull/367 due to merge conflicts. The branch was older as the PR was reviewed late.
- The error is due to accessing the data.answers[0] which can be undefined also
- On logging in, the following console errors are present:
- If message is of type map, the following console errors are given:
This error comes when you use chrome.storage.sync.set.. to set the data which is more than 8,192 bytes for a single item as chrome.storage.sync.set allows 8,192 QUOTA_BYTES_PER_ITEM.
Using chrome.storage.local.set.. to set the data instead of chrome.storage.sync.set.
As chrome.storage.local.set can contains **5242880** :QUOTA_BYTES.
- On logout, following errors are given:
Content Security Policy does not allow inline …
=> Fix Console Error #382, message type Map #366, Persist Susi Reply#402

src/script.js
Fixes #433 
If chat box is already in dark theme mode then after clicking on clear chat the theme would dark theme .
=> clicked on clear chat the dark theme is not changed

src/script.js
Fixes #436 
When the scrollbar is at the middle of the screen then the scroll-bottom button is shown.
=> Updated the scroll button

src/script.js
Fixes #442 
Chrome stores the voice(speaker) settings.
=> Remember voice settings

src/style.css
Fixes #464 
The top and bottom thickness of chat box was reduced.
Before:
-![screenshot 2018-11-07 at 7 57 10 pm](https://user-images.githubusercontent.com/31539812/48146986-45692000-e2dc-11e8-820a-b9e67913ab1c.png)
Now:
=> The top and bottom border thickness of chat box was reduced.

src/js/options.js
Fixes #461 
Restore default button in settings, when clicked shows warning once, instead of twice which was **because of duplicate code present** in options.js file.
=> Restore default button in settings, when clicked shows warning once

src/js/login.js
Fixes #459 
Text of the link that shows/hides change password form, varies depending upon the form is shown or hidden.
GIF - 
-
-
-
=> Change password link text varies now

src/script.js
Fixes #446
Susi chats were getting lost because in script.js for reading the time, wrong
values were being passed which resulted in not defined error, now that bug has been fixed.
=> Susi chats lost after reopening the extension
