fossasia/susi_chromebot

- script.js
Changed script.js to add autoscroll on every message either from user or from susi.
Fixes : https://github.com/fossasia/susi_chromebot/issues/1
Thanks!
> Added Auto Scroll to bottom

- popup.html
- style.css
fixes #4 
@gabru-md @mariobehling Please review.
> chat.susi.ai like UI implemented

- style.css
Added a max-width parameter into style.css to fix issue.
Merge : @zamhaq 
Thanks!
Fixes https://github.com/fossasia/susi_chromebot/issues/20
> Width of Extension Window Fixed

- script.js
Fixed https://github.com/fossasia/susi_chromebot/issues/3
> Fixed Issue #3

- script.js
Fixed https://github.com/fossasia/susi_chromebot/issues/30
Solved major JSLint errors which makes the code well formatted.
> Fixed JSLint errors

- popup.html
Fixed https://github.com/fossasia/susi_chromebot/issues/32
> Fixed Autofocus Issue

- script.js
> Added checks for request error

- style.css
Fixed https://github.com/fossasia/susi_chromebot/issues/35
> Fixed arrow keys

- popup.html
Allows the user to know more about the AI.
> Directs to susi homepage when clicked on the header image

- popup.html
Reverts fossasia/susi_chromebot#37
> Revert "Directs to susi homepage when clicked on the header image"

- popup.html
- style.css
Replaced ordinary "Submit" button with SUSI styled material icon
And style.css is changed for the same.
Closes : https://github.com/fossasia/susi_chromebot/issues/39
PS : @zamhaq Please Review
> Added SUSI Chat Styled Submit Icon

- src/script.js
Fixed https://github.com/fossasia/susi_chromebot/issues/22
Screenshots are attached below
@gabru-md @zamhaq Please review
I have tried to tackle all edge cases review and check if this works well.
> Fixed Image Display

- src/popup.html
- src/style.css
Fixed https://github.com/fossasia/susi_chromebot/issues/49
**Screenshots attached below-**
> Fixed UI Improvements

- src/script.js
Fixes #46 
Added functions for composing message
> add compose message functions

- README.md
Fixed https://github.com/fossasia/susi_chromebot/issues/58
@ms10398 @gabru-md @zamhaq please review
> Added Build Passing Badge [Travis]

- src/script.js
- src/style.css
Fixed https://github.com/fossasia/susi_chromebot/issues/61
Screenshot after change
@zamhaq @gabru-md Have a look
> Added Time Display

- src/popup.html
- src/style.css
Added Anchor tag instead of Button and changed its position
as proposed in UI enhancement.
Fixes : https://github.com/fossasia/susi_chromebot/issues/66
Please review : @zamhaq @ms10398
> Changed Button format to Anchor

- src/popup.html
- src/script.js
- src/style.css
Fixed https://github.com/fossasia/susi_chromebot/issues/63
Screenshots of the change-
Dark Theme-
Light Theme-
@zamhaq @gabru-md 
I have implemented a basic two theme interface. 
There are some little bugs which I want to work upon to make it perfect.
> Add Dark Theme

- src/style.css
> Now the color of submit button matches the susi theme

- src/script.js
Pressing Up/Down keys copies the previous/next message into the text area.
Fixes : https://github.com/fossasia/susi_chromebot/issues/83
> Added UP/DOWN key Event

- README.md
- src/manifest.json
Fixes #92 
- [ x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ x] My branch is up-to-date with the Upstream `nextgen` branch.
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] I have added necessary documentation (if appropriate)
- [ x] All the functions created/modified in this PR contain relevant docstrings.
PR rectified #94 
- Refer #94 
Earlier
Change propsed:
> add icon in the extension management page (chrome://extensions)

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
Add issue template and move Contributing.md to .github to have a uniform structure.
@zamhaq  @gabru-md Please review
> Add issue template

- src/popup.html
- src/script.js
- src/style.css
Fixes https://github.com/fossasia/susi_chromebot/issues/72 https://github.com/fossasia/susi_chromebot/issues/81
There are two commits in the PR as it fixes two different issues.
@zamhaq @gabru-md Please review
> Fix Uneven spaces and Color of Susi messages in dark mode

- .jshintrc
- Gruntfile.js
- src/script.js
- src/style.css
Fixes #80 
- Read correct response
- Support table type response
- Update .jshintrc and Gruntfile.js to support es6 syntax
> read correct response and support table type response

- src/popup.html
- src/script.js
Added button for toggling Speaking voice of SUSI in chromebot
This Commit Fixes the pertaining bug where SUSI Chromebot replies to every query
and then speaks it.
Cheers!
Fixes #110
> added for toggle voice SUSI on/off

- src/script.js
- src/style.css
Fixes https://github.com/fossasia/susi_chromebot/issues/75
It fixes the dark theme errors which were there.
- Full Compatibility for Dark Theme
Sorry for the delay @zamhaq @gabru-md
> Fix Dark Theme Error

- src/script.js
- src/style.css
Fixes  https://github.com/fossasia/susi_chromebot/issues/114
Adjusts the Settings icon with dark theme
- fix issue  Settings icon in Dark theme
> Fix Settings Icon Dark Theme

- README.md
Fixes #134 
Adds a gitter badge in the `README.md` to connect to the gitter channel
- Adds a badge that links [Susi Server](https://gitter.im/fossasia/susi_server) gitter channel
> [ADD] Added gitter communication channel as a badge

- README.md
Fixes #125 
Fixes the broken link for CONTRIBUTING.md
- Fixes the broken url for CONTRIBUTING.md in the main README.md
> [FIX] Fix for broken CONTRIBUTING.md link fixed

- src/style.css
Scrollbar Redesigned
**Before**
**Now**
Improved UI
Scrollbar is now
- thinner and beautiful
- color is according to the theme
> UI Improvement: Scrollbar Redesigned

- src/popup.html
- src/script.js
Fixes https://github.com/fossasia/susi_chromebot/issues/124
Add clear chat button
- Add a clear chat button in the dropdown
> Add Clear Chat Button

- src/popup.html
- src/script.js
Fixes #118 
Open settings page in a separate window rather than a new tab
- Open settings page in a separate window of custom size of 800x800
> Fixes #118: Open settings page in a separate window

- src/manifest.json
- src/script.js
- src/style.css
Fixes #128 and #129 
1)Improves footer layout.Adds right margin to send button and increases width of text area
2)Make text area resizable to none
> #128 #129 #127 #130 UI issues fixed

- src/script.js
Fixes #100
If mic is not allowed user is alerted with a box
@zamhaq @gabru-md review
> Alert user if mic is not allowed

- src/popup.html
- src/script.js
- src/style.css
Fixes #169 
Add a jump to bottom button
> Add jump to bottom button

- src/script.js
- src/style.css
Fixes #166 
Indication for empty chat history
> Add indication for empty history

- src/manifest.json
Fixes #183 
Changed the permissions to fewer.
@zamhaq @gabru-md @stealthanthrax Have a look These are the least required permissions to run the project.
> Changed permissions

- src/script.js
Fixes #186 
Fixes table responses
> Fix table response

- src/settings.css
- src/settings.html
Fixes #191 
Fixes alignment in login page
Fix alignment of login button and logout button in login page
> Fix Alignment in Login Page

- src/allowmic.js
- src/options.html
- src/popup.html
- src/script.js
- src/settings.html
- src/settings_page.css
Fixes #146 via #187 
A new dedicated settings page has been added and custom background feature is also added.
> Added a dedicated settings page and custom background feature

- src/script.js
- src/style.css
Fixes #203 
Jump to bottom button follows dark theme now
> Jump to Bottom Button follows dark theme

- src/css/settings_page.css
- src/js/allowmic.js
- src/options.html
- src/script.js
Fixes #197 
More than two choices added for default themes and minor style changes in ui of settings page
Added the custom themes in settings page
> Added the option of predefined themes

- src/js/allowmic.js
- src/popup.html
- src/script.js
Fixes #232 
Removed all console errors
Removed all console errors
> Remove all console errors

- src/js/allowmic.js
Fixes #242 
Theme is working properly without any errors
Theme is working properly now
> Fixed Theme change

- src/js/login.js
- src/settings.html
Fixes #227 
This fixes the bug of automatically logging out when the page was refreshed
The bug is fixed by adding a check when the window is loaded
> Fixed bug of automatically logging out on refreshing the page

- src/manifest.json
- src/popup.html
- src/script.js
Increasing the standard layout potential of the extension
Closes https://github.com/fossasia/susi_chromebot/issues/252
Adds Options.html to chrome://extensions
> Adds Options page to chrome://extension side.

- src/css/options.css
- src/js/allowmic.js
- src/options.html
- src/script.js
Fixes #238
Added an option to change the color of the message pane.
-change in the CSS and HTML files of the setting page
-change in the script.js and allowmic.js
> Added the option to change the color of the message pane (issue -#238 )

- src/css/recover.css
- src/js/reset.js
- src/recover.html
Fixes #229 
Add option for recover password option
Add option for recover password
@gabru-md @stealthanthrax @arnav-mandal1234 Please review!!
> Add recover password option

- src/js/login.js
- src/script.js
Fixes https://github.com/fossasia/susi_chromebot/issues/228
- Add a Sync feature which syncs User Settings like (Theme) from Api, when a user logs in, 
- Also added another feature where user settings is sent to server if the user is logged in && if it changes the settings. 
P.s auto update settings in localStorage as well  for further cases. and no bugs.
> Add theme sync through login

- src/js/login.js
- src/script.js
Fixes https://github.com/fossasia/susi_chromebot/issues/165
* Get The messages from the api
* Save to local storage and show
* Send messages to the api
- Gets message from susi api
- Show messages from susi api
- Syncs messages to Susi api
> Sync Messages from Server

- src/popup.html
- src/style.css
> Changes Background Color of Scroll-Icon

- src/css/login.css
- src/js/login.js
- src/login.html
Fixes #246
Now the error in logging in is shown using bootstrap alert method.
-
-
-
> fixed:#246

- src/js/signup.js
- src/signup.html
Fixes #270 
Added the option to confirm password
Added the option to confirm password
> Added the option to confirm password

- src/css/options.css
- src/js/allowmic.js
- src/options.html
- src/popup.html
- src/script.js
- src/style.css
Fixes  #202 #193 #261  
* Susi now has a female voice. (#193 )
* UI made agiler (#202 )
* console error fixed (#261 )
> Susi now has a female voice

- src/js/login.js
- src/login.html
Fixes #283 
This adds an option to show password
> Added the option show password like amazon

- src/script.js
Cheers!
Closes : https://github.com/fossasia/susi_chromebot/issues/288
Fixes #288 
Adds Anchor Type Response to SUSI.AI Chromebot
Cheers!
@zamhaq @ms10398 Please Review and merge :)
> Adds Anchor Type Response to SUSI Chromebot

- src/script.js
- src/style.css
Fixes #198 
Added like and dislike buttons
> Added the like and dislike buttons

- src/script.js
- src/style.css
> Revert "Added the like and dislike buttons"

- src/script.js
Fixes #277 
Timestamp strings are showing up correctly
Timestamp strings are showing up correctly now
> Add timetrings with exact server timings

- src/css/login.css
- src/js/login.js
- src/login.html
Fixes #220 
This adds a feature to change password directly through chromebot
> Added the option to change password directly through chromebot

- src/style.css
Fixes #307 
Enable Hand cursor when one hovers over the dropdown menu.
> Enable Hand cursor hovering over dropdown menu

- .github/CONTRIBUTING.md
Adds info about uploading gifs when uploading PRs as a testing strategy. The current documentation does not have the required info
NA
More contributing guidelines regarding testing through gif
> Add info about uploading GIFs on Pull Requests

- src/login.html
Before Change :
After Change :
@gabru-md @zamhaq review pls.
> Fixed errors in login.html

- src/css/login.css
- src/js/login.js
- src/login.html
Fixes #318  #317 #320 
Now Show password filed is non-editable by adding 'disabled' attribute. And use `keyup` event instead of `keypress` to register even the last character types in password field.
> Refactor Show Password UI and logged in message.

- src/manifest.json
Fixes #351
Right click on Logo -> SUSI-AI, Should redirect to github repository
- Redirect to github on SUSI-AI
- Some code indentation
> Redirect to Github Repository on SUSI-AI options #351

- src/signup.html
Fixes https://github.com/fossasia/susi_chromebot/issues/353
- Changed the label from Password to confirm password.
-
-
> changed password to confirm password

- README.md
Fixes #349 
- Update Readme instruction on how to allow mic access.
-
-
> Update instruction on how to allow mic access.

- src/login.html
Fixes #360 
Instead of `btn-success` class, add `btn-danger` class to logout button.
- I have added `btn-danger` class in logout button which makes it red in color. Refer:
- Other available options are:
> Add btn btn-danger class in logout button

- src/popup.html
Fixes #363 
Corrected the code for speech input toggle causing CSP error.
- Fix error: Refused to run the JavaScript URL because it violates the following Content Security
> Fix CSP Error on Mic Toggle #363

- src/script.js
Fixes #314, #365 
Fix error/bug of console. 
Error in response to storage.get: TypeError: Cannot read property 'email' of undefined
- Fix error on extension opening
- Fix console error on switching theme
> Fix cannot read property 'accessToken' of undefined#314, #365

- src/style.css
Fixes #376 
- Makes vertical space between conversation box and input text field smaller.
> Fix space between conversation box and input text field

- src/script.js
Fixes #198 
- [] I have added tests that prove my fix is effective or that my feature works
Enables dislike and like option for user.
First rating object is created using the susi response from the server. Then if `thumbs` up or `thumbsDown` is clicked, then at desired susi server url, a request is sent.
- Code is made as similar as possible to https://github.com/fossasia/chat.susi.ai/blob/master/src/components/ChatApp/MessageListItem/Feedback.react.js
> Add thumbsUp and thumbsDown icons for susi skills feedback

- src/script.js
- src/style.css
Fixes #357
Video support added for messages.
Screenshot:
Note: On clicking the video, its shows `This video is unavailable`. Anyone have some fix or can take this up in a new PR maybe.
GIF:
- Video support
> Add video support for SUSI Replies #357

- .jshintrc
- Gruntfile.js
- src/script.js
- src/style.css
Fixes #396, #397, #400, #395
Add share functionality for user. Format message window.
Screen shot:
Old:
New:
Fixed time response:
Share functionality GIF:
- Add share functionality
- Fix formatting of message responses
- Fix Date if Error on Fetching Response
- Remove Message Ticks to Match Web App
> Fix message format #396, #397, #400, Add Share support #395

- src/js/background.js
- src/js/login.js
- src/js/options.js
- src/js/reset.js
- src/js/signup.js
- src/script.js
Fixes #170 one task.
Converted all the function in es5 to es6 fat arrow functions, in all js files.
Solves the issues, first part.
@zamhaq @ms10398 @gabru-md  let me know if this is how you guys wanted.
> Change functions to es6 arrow functions

- src/popup.html
- src/script.js
- src/style.css
Fixes #342 
Closed PR https://github.com/fossasia/susi_chromebot/pull/371 due to some multiple merge conflicts.
Added scroll to top functionality
- Scroll to top
- Code indentation
- Removed redundant new lines
> Add scroll to top in scroll window #342

- .gitignore
Fixes #428 
@ms10398 @zamhaq @rupav merge this?
thanks
> Adds .idea to .gitignore

- src/js/login.js
Fixes #389 
When eye is closed the password should be hidden and vice-versa
> eye slash fixed

- src/js/options.js
- src/options.html
- src/popup.html
- src/script.js
- src/style.css
Fixes #394, #407, #406
Closed https://github.com/fossasia/susi_chromebot/pull/399, due to merge conflicts which couldn't be solved, not detected in my IDE.
Adds single material icon for sending message or using voice input, like in web chat.
GIF:
- Change naming for submit in options.js: Naming submit1, submit2, submit3 meaningfully
- Solves: Uncaught TypeError: Cannot read property 'addEventListener' of null at options.js:106
- Modify Compose Message Similar to Web App
> Fix #394, #407, #406

- src/style.css
> Fixed time size

- src/js/login.js
- src/login.html
Fixes #453 
When user has logged in and trying to change the password then there is no need of email textfield that's why Email textfield is removed.
> Removed email field

- src/css/login.css
- src/js/login.js
- src/login.html
Fixes #478 
Added confirm password field in change password field.
> Added confirm password field

- src/js/login.js
Fixes #469
Email field validation is now improved. 
Now Email validation is done properly according to regex
Screenshot -
GIF-
> Email validation improved in login page

- src/script.js
Fixes #440 
When no message is typed. The window should show Start by saying "Hi" at the top of the window
> Displaying starting text

- .github/ISSUE_TEMPLATE.md
Fixes #489 
Issue template now asks for screenshots. Also, the line `Please let us know if you can work on it or the issue should be assigned to someone else` only conveys message to user, so was commented.
> Issue template imporved

- .github/ISSUE_TEMPLATE.md
Fixes: #511 
Currently, 'check one with "x" ' in issue template is not in comments and looks abrupt after the issue is opened. But it should be in comments.
- 'check one with "x" ' is commented.
> modify issue template

- src/js/options.js
Fixes #503 
It checks the validity of background URL provided
> Function to check valid extension for Background image URL added

- src/js/login.js
Fixes #470
When all fields are valid then only submit button will be enabled.
> Form validation in change password form

- src/js/options.js
Fixes #505 
-"Added Button to login on Settings page"
> "Added Button to login on Settings page"

- src/script.js
Fixes #526 
When clicked on clear chat voice settings is same as before.
> Voice settings is not changed when clicked clear chat

- src/js/options.js
Fixes #515
Fixing Color picker error and other undefined errors
> Fixing Color picker and other Undefined  errors

- src/script.js
Fixes #535 
It will fix the clear chat button.
> fixes #535 'clear chat' button bug
